version: "3.8"

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_vuln_app
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
    restart: unless-stopped
